### ISSUE TITLE
Login form

### ISSUE THREAD

**Issue by TildaDares** [kwambugu/Jumpstart-Lab-s-Blogger-Tutorial#2]
Hi sorry to bother you again. I just completed the Authentication section of the blogger tutorial but whenever I click on the login page I'm redirected to the index page. I've retraced my steps and tried to figure out where the problem is coming from but I found nothing wrong.

**Comment by Clinton-dev** [comment]
Maybe it could be the route path that u are Givin it

**Comment by TildaDares** [comment]
I don't see anything wrong with it. It was working before I put in the before_action methods in the controllers.

**Comment by Clinton-dev** [comment]
where should you be directed when you successfully login

**Comment by Clinton-dev** [comment]
also you could also check to see if the before_action methods are available in ur current version of rails

**Comment by TildaDares** [comment]
It should redirect back to the index page after login

**Comment by Clinton-dev** [comment]
are there any users in the system?

**Comment by TildaDares** [comment]
Yeah

**Comment by TildaDares** [comment]
Okay so when I removed this line from the AuthorSessionsController the login form started working.
before_action :require_login, only: [:new, :create, :destroy]. I don't know why it's like that though.

**Comment by Clinton-dev** [comment]
could you try before_filter:require_login and see if it works

**Comment by TildaDares** [comment]
It's working now. Thank you
